fix: keep original input formatting when returning
snapshot-labs/stamp pull request #156
Opened 2023-12-13 11:43 UTC by wa0x6e

Fix #155

2024-01-14 10:22 UTC, ChaituVR requested changes
Sorry for delay on this,

It works well with names but not with addresses, try
```
{
    "method": "lookup_addresses",
    "params": [
        "0xeF8305E140ac520225DAf050e2f71d5fBcC543e7",
        "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
    ]
}
```

then

```
{
    "method": "lookup_addresses",
    "params": [
        "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
    ]
}
```
Second will not return any response, this is fine?

2024-01-14 10:35 UTC, wa0x6e commented
> Sorry for delay on this,
> 
> It works well with names but not with addresses, try
> 
> ```
> {
>     "method": "lookup_addresses",
>     "params": [
>         "0xeF8305E140ac520225DAf050e2f71d5fBcC543e7",
>         "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
>     ]
> }
> ```
> 
> then
> 
> ```
> {
>     "method": "lookup_addresses",
>     "params": [
>         "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
>     ]
> }
> ```
> 
> Second will not return any response, this is fine?

No, this is not fine

2024-01-14 10:37 UTC, wa0x6e commented
> 0xEF8305E140AC520225DAF050E2F71D5FBCC543e7

I don't get same result:

```bash
curl -X POST http://localhost:3008/ -H "Content-Type: application/json" -d '{"method": "lookup_addresses", "params": ["0xeF8305E140ac520225DAf050e2f71d5fBcC543e7", "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"] }'

{"jsonrpc":"2.0","result":{"0xeF8305E140ac520225DAf050e2f71d5fBcC543e7":"fabien.eth","0xEF8305E140AC520225DAF050E2F71D5FBCC543e7":"fabien.eth"},"id":null}
```

2024-01-15 06:57 UTC, wa0x6e commented
> > Sorry for delay on this,
> > It works well with names but not with addresses, try
> > ```
> > {
> >     "method": "lookup_addresses",
> >     "params": [
> >         "0xeF8305E140ac520225DAf050e2f71d5fBcC543e7",
> >         "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then
> > ```
> > {
> >     "method": "lookup_addresses",
> >     "params": [
> >         "0xEF8305E140AC520225DAF050E2F71D5FBCC543e7"
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Second will not return any response, this is fine?
> 
> No, this is not fine

Should be fixed, please retest

2024-01-15 07:05 UTC, ChaituVR approved these changes
tAck

2024-01-15 07:06 UTC, merged