fix: fix address formatter for starknet address
snapshot-labs/stamp pull request #229
Opened 2024-05-29 11:29 UTC by wa0x6e

This PR skip the address formatting when it is a starknet address, and also add more tests

2024-05-29 18:33 UTC, ChaituVR requested changes

2024-05-29 18:33 UTC, ChaituVR commented on src/resolvers/space-sx.ts
> +          spaces(where: { id_in: ["${id.join('", "')}"] }) {
maybe this is much better
```suggestion
          spaces(where: { id_in: [${id.map(item => `"${item}"`).join(', ')}] }) {
```

2024-05-29 18:33 UTC, ChaituVR commented
Looks like test cases are still failing some how 🤔

2024-05-29 19:46 UTC, wa0x6e commented
> Looks like test cases are still failing some how 🤔

Failing tests are unrelated, they're now failing due to something wrong with the starknet library itself, and not due to tests themselves, issue has been open https://github.com/snapshot-labs/stamp/issues/230

2024-05-30 05:20 UTC, ChaituVR approved these changes
utAck

2024-05-30 09:31 UTC, merged