fix: use address formatter from SDK
snapshot-labs/stamp pull request #251
Opened 2024-07-05 05:59 UTC by wa0x6e

2024-07-05 06:31 UTC, ChaituVR requested changes

2024-07-05 06:31 UTC, ChaituVR commented on src/resolvers/snapshot.ts
> -import { getChecksummedAddress } from '../utils';
We are not using getChecksummedAddress anywhere, maybe we can delete it from utils

2024-07-05 06:49 UTC, ChaituVR requested changes

2024-07-05 06:49 UTC, ChaituVR commented on src/utils.ts
![Untitled 5](https://github.com/snapshot-labs/stamp/assets/15967809/4f137d2f-58b9-445b-ad1c-9fe28b74b826)

2024-07-17 08:04 UTC, wa0x6e commented
Closing, will let hub decide how to format the address

2024-07-17 08:04 UTC, closed without merging